name: CI-DockerImage

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"
    workflow_dispatch:

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22

            - name: Verify dependencies
              run: go mod verify

            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...

    push_to_docker_hub:
        runs-on: ubuntu-latest
        needs: [build]

        steps:
            - name: checkout repo
              uses: actions/checkout@v2

            - name: Build and Push Docker image
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                  image: ${{ secrets.DOCKER_USERNAME }}/postgres_pro
                  tags: latest
                  dockerFile: docker/Dockerfile
                  registry: docker.io
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
